### ISSUE TITLE
Dark Mode

### ISSUE THREAD

**Issue by CurlyBracketEffect** [1Hive/celeste-dashboard#40]
I always prefer a dark mode on any site that offers it. It generally saves on battery and is easier on the eyes.  I like how dark mode on Honeyswap is kind of greeny-blue with a little yellow. But I think Celeste has a different colour scheme and would look really good with some dark purple and pink highlights. To take it one step further it would look really cool if it had a starry sky kind of look in the background a dark purple background with pink and yellow stars.

**Comment by fioreb** [comment]
[https://app.zenhub.com/files/309829079/f1769556-8d6f-4b8c-9151-312cd08883a3/download](https://app.zenhub.com/files/309829079/f1769556-8d6f-4b8c-9151-312cd08883a3/download)

**Comment by fioreb** [comment]
@fabriziovigevani here is the file with the icons for the Global preferences.
I add the dark mode icon for the light theme too because we didn't have it.

[https://app.zenhub.com/files/309829079/60f77fa2-abeb-4c22-a1cb-916d812c71a6/download](https://app.zenhub.com/files/309829079/60f77fa2-abeb-4c22-a1cb-916d812c71a6/download)

**Comment by fabriziovigevani** [comment]
closed by #110
