### ISSUE TITLE
The sidepanel of Confirm action doesn't have the cross to close it

### ISSUE THREAD

**Issue by fioreb** [1Hive/celeste-dashboard#62]
<img width="690" alt="Screen Shot 2021-03-03 at 11 37 17" src="https://user-images.githubusercontent.com/61423083/110386101-a042eb80-803e-11eb-8dd9-6187b8ceeaa3.png">

**Comment by CurlyBracketEffect** [comment]
I have encountered this as well. I initiated the confirm action transaction flow, and then rejected the transaction but the side panel stays open. I can select the navigation tabs on the left side of the screen, but the main viewing area remains covered with a slightly transparent layer. I can see that the main viewing area changes to the desired page but I cannot interact with it at all. I need to refresh the page in order to get around the bug.
