### ISSUE TITLE
No Dispute Action label for signalling proposal or decisions.

### ISSUE THREAD

**Issue by willjgriff** [1Hive/celeste-dashboard#96]
Can this dispute https://celeste-rinkeby.1hive.org/#/disputes/4 show the Disputed Action title or at least link to the disputed action in the Honey Pot? I believe it should be related to this signalling proposal: https://honey-pot-git-disputable-version-1hive.vercel.app/#/proposal/10

Also this vote https://honey-pot-git-disputable-version-1hive.vercel.app/#/vote/1 is associated with this dispute https://celeste-dashboard.vercel.app/#/disputes/5 but there's no link back to it in the "Disputed Action" label:
<img width="904" alt="Screenshot 2021-03-18 at 13 58 16" src="https://user-images.githubusercontent.com/9317743/111638276-13dcb980-87f2-11eb-8735-32dc2e92d886.png">

Also what's the deal with the "Failed to load" message that happened for one proposal during the QA party? I see the proposal has a Disputed Action now, should that error be fixed?

**Comment by fabriziovigevani** [comment]
Will check if we have a way to fetch the proposal metadata from the subgraph, unfortunately this will not be a general solution, since the hineypot subgraph only tracks our DAO. We could actually have a mapping of `artibtrable => function for extracting metadata, description`. Currently the mapping is `disputableApp name => function to extract metadata description` but we could make it more granular with the first mapping described. Any other organization plug in to Celeste, sohuld afterwards make a PR or tell us how their metadata is fetched.

> Also what's the deal with the "Failed to load" message that happened for one proposal during the QA party? I see the proposal has a Disputed Action now, should that error be fixed?

Yeah this issue is definitely odd, it's basically erroring on `convictionVoting.getProposal(disputableActionId)`. Will get it sorted out.
